// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: del_users.sql

package database

import (
	"context"
)

const deleteAll = `-- name: DeleteAll :exec
DELETE FROM users
`

func (q *Queries) DeleteAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAll)
	return err
}
