// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_chirp.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteChirp = `-- name: DeleteChirp :execresult
delete from chirps where id = $1 and user_id = $2
`

type DeleteChirpParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChirp(ctx context.Context, arg DeleteChirpParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteChirp, arg.ID, arg.UserID)
}
