// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revoke_token.sql

package database

import (
	"context"
)

const revokeToken = `-- name: RevokeToken :exec
update refresh_tokens set revoked_at = NOW() where token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
