// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: set_chirpy_red.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const setChirpyRed = `-- name: SetChirpyRed :execresult
update users set is_chirpy_red = TRUE where id = $1
`

func (q *Queries) SetChirpyRed(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, setChirpyRed, id)
}
