name: ci
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start database
        run: docker compose -f compose.yaml up --build -d db
      - name: Run migrations
        run: docker compose -f compose.yaml run --rm migrate
      - name: Run API tests
        run: docker compose -f compose.yaml up --build --exit-code-from tests api tests
      - name: Clean up
        if: always()
        run: docker compose -f compose.yaml down -v