name: ci
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start database
        run: docker compose -f compose.yaml up --build -d db
      - name: Run migrations
        run: docker compose -f compose.yaml run --rm migrate
      - name: Run API tests
        run: docker compose -f compose.yaml up --build --exit-code-from tests api tests
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-junit-report
          path: reports/junit.xml
      - name: Publish JUnit report
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: reports/junit.xml
      - name: Upload HTML Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pytest-reports
          path: reports/test_report.html
      - name: Clean up
        if: always()
        run: docker compose -f compose.yaml down -v
